name: Deploy Svelte with GitHub Pages

on:
  push:
    branches: ['main']

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build-cv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: sudo apt-get install -y latexmk texlive-latex-extra
      - name: Build
        run: |
          cd cv-latex
          make
      - uses: actions/upload-artifact@v4
        with:
          name: cv-latex
          path: cv-latex

  build-godot:
    runs-on: ubuntu-latest
    env:
      GODOT_VERSION: 4.2.2
    container:
      image: barichello/godot-ci:4.2.2
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Build
        run: |
          mkdir build
          cd godot-web-test
          godot --headless --export-release Web $(dirname $(pwd))/build/godot-test.html
      - name: Fix problem with Github Pages headers
        run: |
          cd build
          wget https://raw.githubusercontent.com/gzuidhof/coi-serviceworker/master/coi-serviceworker.min.js 
          sed  '/\<head\>/a \<script src="coi-serviceworker.min.js"\>\</script\>' godot-test.html > temp.html
          mv temp.html godot-test.html
      - uses: actions/upload-artifact@v4
        with:
          name: godot
          path: build

  build-svelte:
    runs-on: ubuntu-latest
    needs: [build-cv]
    steps:
      - uses: actions/download-artifact@v4
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install
        run: npm install
      - name: Check
        run: npm run check && npm run lint
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: svelte
          path: build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [build-godot, build-svelte]
    steps:
      - uses: actions/configure-pages@v4
      - uses: actions/download-artifact@v4
      - name: Unpack artefacts
        run: |
          mkdir build
          mv godot/* svelte/* build
      - name: Debug
        run: ls -R
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build
      - uses: actions/deploy-pages@v4
        id: deployment
